"""Numerical-identity regression: feature outputs are frozen, bit-for-bit (float32 floor).

Fixtures in ``tests/fixtures/research_ref.npz`` were originally generated by the
private research ``bispectrum`` package. They were regenerated from bispectrosa
itself on 2026-07-17, freezing five deliberate output changes:
``raw_bispectrum``'s exact sum-frequency sampling (``i3 = i1 + i2``), its
move to the STFT's native bin grid (``n_grid`` resampling removed), the
mean-free default window ``kmin=1`` (``direct_B`` starts at the first nonzero
frequency; values on shared cells bit-identical to the previous grid), and
the modal estimator's constant third leg (every pair kernel weights its
third leg by the window's indicator, not by mode order 0; the mel beta
entries changed accordingly). Regenerate only for a further deliberate
output change.
"""

from pathlib import Path

import numpy as np
import pytest

import bispectrosa as bs

FIX = Path(__file__).parent / "fixtures" / "research_ref.npz"


@pytest.fixture(scope="module")
def ref():
    return np.load(FIX)


def test_mel_bispectrogram_pooled(ref):
    y = ref["y"]
    got = bs.time_pool(bs.mel_bispectrogram(y, sr=16000, degree=12))  # (49,)
    np.testing.assert_allclose(got, ref["mel_modal_pair_pooled"], rtol=1e-5, atol=1e-4)


def test_mel_bispectrogram_frames(ref):
    y = ref["y"]
    got = bs.mel_bispectrogram(y, sr=16000, degree=12).T  # (T, 49)
    np.testing.assert_allclose(got, ref["mel_modal_pair_frames"], rtol=1e-5, atol=1e-4)


def test_degree_ordered_prefix_property():
    # first modal_pair_dim(d) entries of a higher-degree list == the degree-d list
    hi = bs.modal_index_pairs(12)
    for d in (7, 10):
        assert hi[: bs.modal_pair_dim(d)] == bs.modal_index_pairs(d)


def test_raw_bispectrum_matches_reference(ref):
    y = ref["y"]
    k1, k2, vals = bs.raw_bispectrum(bs.stft(y))
    R = ref["direct_B"]
    # scatter the flat values back into the historical half-NaN layout
    B = np.full(R.shape, np.nan)
    B[k1 - k1.min(), k2 - k1.min()] = vals
    both = np.isfinite(B) & np.isfinite(R)
    assert both.sum() > 0
    np.testing.assert_allclose(B[both], R[both], rtol=1e-4, atol=1e-4)
    # the NaN valid-region mask must line up exactly
    assert np.array_equal(np.isfinite(B), np.isfinite(R))
